//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistInfoDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistAlia
    {
        public long Id { get; set; }
        public System.Guid ArtistId { get; set; }
        public string Alias { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
