//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessment.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public long ArtistID { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
        public long CountryID { get; set; }
        public string Name { get; set; }
    }
}
