// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Structure.Contracts.MusicBrainz
{

    public class Alias
    {

        [JsonProperty("sort-name")]
        public string SortName { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("locale")]
        public object Locale { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("primary")]
        public object Primary { get; set; }

        [JsonProperty("begin-date")]
        public object BeginDate { get; set; }

        [JsonProperty("end-date")]
        public object EndDate { get; set; }
    }

}
