// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Structure.Contracts.MusicBrainz
{

    public class ArtistCredit
    {

        [JsonProperty("artist")]
        public Artist Artist { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("joinphrase")]
        public string Joinphrase { get; set; }
    }

}
