// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Structure.Contracts.MusicBrainz
{

    public class LabelInfo
    {

        [JsonProperty("label")]
        public Label Label { get; set; }

        [JsonProperty("catalog-number")]
        public string CatalogNumber { get; set; }
    }

}
