// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Structure.Contracts.MusicBrainz
{

    public class Medium
    {

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("disc-count")]
        public int DiscCount { get; set; }

        [JsonProperty("track-count")]
        public int TrackCount { get; set; }
    }

}
