// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Structure.Contracts.MusicBrainz
{

    public class Release
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("score")]
        public string Score { get; set; }

        [JsonProperty("count")]
        public int Count { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("packaging")]
        public string Packaging { get; set; }

        [JsonProperty("text-representation")]
        public TextRepresentation TextRepresentation { get; set; }

        [JsonProperty("artist-credit")]
        public ArtistCredit[] ArtistCredit { get; set; }

        [JsonProperty("release-group")]
        public ReleaseGroup ReleaseGroup { get; set; }

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("release-events")]
        public ReleaseEvent[] ReleaseEvents { get; set; }

        [JsonProperty("barcode")]
        public string Barcode { get; set; }

        [JsonProperty("asin")]
        public string Asin { get; set; }

        [JsonProperty("label-info")]
        public LabelInfo[] LabelInfo { get; set; }

        [JsonProperty("track-count")]
        public int TrackCount { get; set; }

        [JsonProperty("media")]
        public Medium[] Media { get; set; }

        [JsonProperty("disambiguation")]
        public string Disambiguation { get; set; }
    }

}
