// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Structure.Contracts.MusicBrainz
{

    public class ReleaseEvent
    {

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("area")]
        public Area Area { get; set; }
    }

}
