// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Structure.Contracts.MusicBrainz
{

    public class TextRepresentation
    {

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("script")]
        public string Script { get; set; }
    }

}
