USE [master]
GO

/****** Object:  Database [Assessment]    Script Date: 2015/10/11 4:11:31 PM ******/
CREATE DATABASE [Assessment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assessment', FILENAME = N'F:\Installs\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\Assessment.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Assessment_log', FILENAME = N'F:\Installs\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\Assessment_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Assessment] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assessment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Assessment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Assessment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Assessment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Assessment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Assessment] SET ARITHABORT OFF 
GO

ALTER DATABASE [Assessment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Assessment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Assessment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Assessment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Assessment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Assessment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Assessment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Assessment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Assessment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Assessment] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Assessment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Assessment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Assessment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Assessment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Assessment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Assessment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Assessment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Assessment] SET RECOVERY FULL 
GO

ALTER DATABASE [Assessment] SET  MULTI_USER 
GO

ALTER DATABASE [Assessment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Assessment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Assessment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Assessment] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Assessment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Assessment] SET  READ_WRITE 
GO


/* For security reasons the login is created disabled and with a random password. */
/****** Object:  Login [assessment]    Script Date: 2015/10/11 4:12:09 PM ******/
CREATE LOGIN [assessment] WITH PASSWORD=N'KJóieàC;ÜB`&±n<àAÕ«³§ùË', DEFAULT_DATABASE=[Assessment], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

ALTER LOGIN [assessment] DISABLE
GO
